config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/trend' => 'pages#trend'
  get '/search' => 'pages#search'
  get '/post' => 'pages#post'

  resources :museums, only: [:index, :show]

  resources :logs, only: [:new, :create, :edit, :update]
  resources :art_logs, only: [:edit, :update]

  resources :exhibitions, only: [:index, :show] do
    resources :exhb_pins, only: [:create, :destroy]
  end

  resources :exhb_logs, only: [:show, :destroy] do
    resources :exhb_log_likes, only: [:create, :destroy]
    resources :exhb_log_comments, only: [:create, :destroy]
  end

  get 'exhb_logs/:id/exhb_log_comments' => 'exhb_logs#show'

  resources :arts, only: [:index, :show] do
    resources :art_logs, only: [:new, :create]
  end

  resources :art_logs, only: [:show, :destroy] do
    resources :art_log_likes, only: [:create, :destroy]
    resources :art_log_comments, only: [:create, :destroy]
  end

  get 'art_logs/:id/art_log_comments' => 'art_logs#show'

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }

  get 'articles/admin' => 'articles#admin_index'
  patch 'articles/:id/publish' => "articles#publish"
  put 'articles/:id/publish' => "articles#publish"
  patch 'articles/:id/unpublish' => "articles#unpublish"
  put 'articles/:id/unpublish' => "articles#unpublish"
  resources :articles

  get '/mypage' => 'users#mypage'
  get '/:username' => 'users#show'
  get '/:username/edit' => 'users#edit'
  patch '/:username' => 'users#update'
end

app/models/article.rb
class Article < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy, :publish, :unpublish]
  before_action :auth_admin, except: [:index, :show]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all.where(published: true).order(id: "DESC")
  end

  def admin_index
    @articles = Article.all.order(id: "DESC")
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    if !user_signed_in? || (user_signed_in? && current_user.email != "admin@doodo.jp")
      if !@article.published
        redirect_to articles_path
      end
    end
    @title = "#{@article.title}｜アートの口コミサイト【doodo】"
    @description = @article.description
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to articles_admin_path
    else
      redirect_to new_article_path
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    if @article.update(article_params)
      redirect_to articles_admin_path
    else
      redirect_to new_article_path
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    redirect_to articles_admin_path
  end

  def publish
    @article.update(published: true)
    redirect_to session[:previous_url] || root_path
  end

  def unpublish
    @article.update(published: false)
    redirect_to session[:previous_url] || root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:image, :title, :body, :description, :published)
    end

    def auth_admin
      if !user_signed_in? || current_user.email != "admin@doodo.jp"
        redirect_to articles_path
      end
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<div class="row">
  <div class="col-6 col-12-xsmall">
    <%= form_with(model: article, local: true) do |form| %>
      <% if article.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

          <ul>
          <% article.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="article-form mb10">
        <%= form.file_field :image, class: "non-active" %>
        <div id="upload_image_button" class="button" onclick="$('#article_image').click()">サムネ画像をアップロード</div>
      </div>

      <div class="article-form mb10">
        <%= form.text_field :title, placeholder: "タイトル" %>
      </div>

      <div class="article-form mb10">
        <%= form.text_area :body, rows: "30", placeholder: "本文" %>
      </div>

      <div class="article-form mb10">
        <%= form.text_area :description, placeholder: "ディスクリプション" %>
      </div>

      <div class="article-form align-center mb10">
        <%= form.radio_button :published, :false, checked: true %>
        <%= form.label :published, "公開しない", {value: :false, style: "display: inline-block;"} %>
        <%= form.radio_button :published, :true %>
        <%= form.label :published, "公開する", {value: :true, style: "display: inline-block;"} %>
      </div>

      <div class="article-submit-buttons">
        <%= link_to 'キャンセル', articles_admin_path, data: { confirm: "変更を破棄しますか？" }, class: "button" %>
        <div id="temp_save_button">
          <%= form.submit "一時保存する" %>
        </div>
        <div id="publish_button">
          <%= form.submit "　公開する　", data: { confirm: "本当に公開しますか？" }, class: "primary" %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="col-6 col-12-xsmall">
    <div class="adjust-box box-16x9">
      <div class="inner-box align-center">
        <div id="preview_image" class="w100 h100">
          <%= image_tag @article.image.to_s, class: "image w100 h100", style: "object-fit:cover;" %>
        </div>
      </div>
    </div>
    <h2 id="preview-title"></h2>
    <div id="preview-body"></div>
  </div>
</div>


<%= javascript_include_tag 'marked.js' %>

<script type="text/javascript" language="javascript">
  marked.setOptions({breaks : true});

  $articleImage = $('#article_image');
  $articleTitle = $('#article_title');
  $articleBody = $('#article_body');
  $articlePublishedFalse = $('#article_published_false');
  $articlePublishedTrue = $('#article_published_true');
  $previewTitle = $('#preview-title');
  $previewImage = $('#preview_image');
  $previewBody = $('#preview-body');

  // ロード時
  $previewTitle.html(
    marked($articleTitle.val())
  );

  $previewBody.html(
    marked($articleBody.val())
  );

  if ($articlePublishedTrue[0].checked) {
    $('#temp_save_button').addClass("non-active");
    $('#publish_button').removeClass("non-active");
  } else {
    $('#temp_save_button').removeClass("non-active");
    $('#publish_button').addClass("non-active");
  }

  // 編集時
  $($articleImage).on('change', $articleImage, function(e) {
    file = e.target.files[0];
    reader = new FileReader();

    if(file.type.indexOf('image') < 0){
      return false;
    };

    reader.onload = (function(file) {
      return function(e) {
        $previewImage.empty();
        $previewImage.append($('<img>').attr({
          src: e.target.result,
          width: "100%",
          height: "100%",
          class: "image",
          style: "object-fit:cover;",
          title: file.name
        }));
      };
    })(file);
    reader.readAsDataURL(file);
  });

  $articleTitle.on('input', function() {
    $previewTitle.html(
      marked($articleTitle.val())
    );
  });

  $articleBody.on('input', function() {
    $previewBody.html(
      marked($articleBody.val())
    );
  });

  $articlePublishedFalse.on('click', function() {
    $('#temp_save_button').removeClass("non-active");
    $('#publish_button').addClass("non-active");
  });
  $articlePublishedTrue.on('click', function() {
    $('#temp_save_button').addClass("non-active");
    $('#publish_button').removeClass("non-active");
  });
</script>

app/views/articles/admin_index.html.erb
<div class="row">
  <div class="off-2 col-8 off-0-xsmall col-12-xsmall">
    <div class="row mt10">
      <div class="col-6 align-center">
        <%= link_to new_article_path, class: "button primary" do %>
          <i class="fas fa-feather-alt"></i>
          新規投稿
        <% end %>
      </div>
      <div class="col-6 align-center">
        <%= link_to articles_path, class: "button" do %>
          <i class="fas fa-feather-alt"></i>
          公開中の記事一覧へ
        <% end %>
      </div>
    </div>

    <% @articles.each do |article| %>
      <%= link_to article_path(article) do %>
        <div class="article-container">
          <% if article.image.present? %>
            <div class="adjust-box box-16x9">
              <div class="inner-box align-center">
                <%= image_tag article.image.to_s, class: "image w100 h100", style: "object-fit: cover;" %>
              </div>
            </div>
          <% end %>

          <h2 class="article-title mt10 mb5">
            <%= article.title %>
          </h2>

          <div class="gray mb5">
            <%= l article.updated_at, format: :short_date %>
          </div>

          <div class="bb0">
            <% if article.published? %>
              <div class="mb10">
                <span class="dark">ステータス：</span>
                <i class="fas fa-cloud dark"></i>
                <span class="bold dark">公開</span>
              </div>

              <div>
                <%= link_to "/articles/#{article.id}/unpublish", method: :patch, data: { confirm: 'ほんとに非公開にしちゃうの？' }, class: "mb5 button dark" do %>
                  <i class="fas fa-pause pink"></i>
                  非公開にする
                <% end %>
                <%= link_to edit_article_path(article), class: "mb5 button dark" do %>
                  <i class="fas fa-edit pink"></i>
                  編集する
                <% end %>
                <%= link_to article, method: :delete, data: { confirm: 'Are you sure?' }, class: "mb5 button" do %>
                  <i class="far fa-trash-alt"></i>
                  削除する
                <% end %>
              </div>

            <% else %>
              <div class="mb10">
                <span class="dark">ステータス：</span>
                <i class="fas fa-pause pink"></i>
                <span class="bold pink">非公開</span>
              </div>

              <div>
                <%= link_to "/articles/#{article.id}/publish", method: :patch, data: { confirm: 'ほんとに公開する？' }, class: "mb5 button dark" do %>
                  <i class="fas fa-cloud-upload-alt pink"></i>
                  公開する
                <% end %>
                <%= link_to edit_article_path(article), class: "mb5 button dark" do %>
                  <i class="fas fa-edit pink"></i>
                  編集する
                <% end %>
                <%= link_to article, method: :delete, data: { confirm: 'Are you sure?' }, class: "mb5 button" do %>
                  <i class="far fa-trash-alt"></i>
                  削除する
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="mt20">編集</h1>

<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<div class="row">
  <div class="off-2 col-8 off-0-xsmall col-12-xsmall">
    <% @articles.each do |article| %>
      <%= link_to article_path(article) do %>
        <div class="article-container">
          <div class="adjust-box box-16x9">
            <div class="inner-box align-center">
              <%= image_tag article.image.to_s, class: "image w100 h100", style: "object-fit: cover;" %>
            </div>
          </div>

          <h2 class="article-title mt10 mb5">
            <%= article.title %>
          </h2>

          <div class="gray">
            <%= l article.updated_at, format: :short_date %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/articles/new.html.erb
<h1 class="mt20">新規投稿</h1>

<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<%= hidden_field_tag "articleBody", @article.body %>

<div class="row">
  <div class="off-2 col-8 off-0-xsmall col-12-xsmall">
    <div class="article-show-container">
      <div class="adjust-box box-16x9">
        <div class="inner-box align-center">
          <%= image_tag @article.image.to_s, class: "image w100 h100", style: "object-fit: cover;" %>
        </div>
      </div>
      <h1 class="bold dark mt10 mb0" style="font-size:1.8em"><%= @article.title %></h1>
      <div class="mb20 gray"><%= l @article.updated_at, format: :short_date %></div>
      <div id="preview-body"></div>

      <div class="w100 align-center mb20">
        <%= link_to articles_path, class: "button" do %>
          <i class="fas fa-feather-alt"></i>
          一覧へ戻る
        <% end %>
      </div>

      <div class="w100 align-center">
        <%= link_to root_path, class: "bb0" do %>
          <%= image_tag 'doodo-logo.png', class: "article-show--footer-logo" %>
        <% end %>
      </div>
      <h2 class="align-center mb10">
        doodoで気軽にアートを学ぼう！
      </h2>
      <div class="align-center mb10">
        <div class="align-center mb5">
          <strong>doodo（ドゥードゥー）</strong>では、<span class="pink">有名なアーティストの作品</span>を
          <br>
          他にもたくさん学ぶことができます！
        </div>
        <div class="align-center mb5">
          お互いに<span class="pink">感想をシェア</span>して、<br class="br-sp">新しいアートの楽しみ方を見つけてみませんか？
        </div>
        <div class="align-center mb5">
          <div>あとから自分の感想を<span class="pink">振り返る</span>のもおすすめです！</div>
        </div>
        <div class="mt10 row">
          <div class="col-6">
            <%= link_to 'ランキングを見る', root_path, class: "button primary" %>
          </div>
          <div class="col-6">
            <%= link_to 'みんなの感想を見る', root_path(t: 'newpost'), class: "button primary" %>
          </div>
        </div>
      </div>

      <% if is_admin? %>
        <div>
          <% if @article.published %>
            <div class="mb10">
              <span class="dark">ステータス：</span>
              <i class="fas fa-cloud dark"></i>
              <span class="bold dark">公開</span>
            </div>
            <%= link_to "/articles/#{@article.id}/unpublish", method: :patch, data: {confirm: 'ほんとに非公開にしちゃうの？'}, class: "mb5 button dark" do %>
              <i class="fas fa-pause pink"></i>
              非公開にする
            <% end %>
          <% else %>
            <div class="mb10">
              <span class="dark">ステータス：</span>
              <i class="fas fa-pause pink"></i>
              <span class="pink">非公開</span>
            </div>
            <%= link_to "/articles/#{@article.id}/publish", method: :patch, data: {confirm: 'ほんとに公開する？'}, class: "mb5 button dark" do %>
              <i class="fas fa-cloud-upload-alt pink"></i>
              公開する
            <% end %>
          <% end %>
          <%= link_to edit_article_path(@article), class: "button dark" do %>
            <i class="fas fa-edit pink"></i>
            編集する
          <% end %>
          <%= link_to articles_admin_path, class: "mb5 button dark bb0" do %>
            <i class="fas fa-hammer pink"></i>
            管理画面へ戻る
          <% end %>

          <%= link_to @article, method: :delete, data: {confirm: '本当に削除する？'}, class: "button" do %>
            <i class="far fa-trash-alt"></i>
            削除する
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>


<%= javascript_include_tag 'marked.js' %>

<script type="text/javascript" language="javascript">
    marked.setOptions({breaks: true});

    $('#preview-body').html(
        marked(articleBody.value)
    );
</script>