config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/trend' => 'pages#trend'
  get '/search' => 'pages#search'
  get '/post' => 'pages#post'

  resources :museums, only: [:index, :show]

  resources :logs, only: [:new, :create, :edit, :update]
  resources :art_logs, only: [:edit, :update]

  resources :exhibitions, only: [:index, :show] do
    resources :exhb_pins, only: [:create, :destroy]
  end

  resources :exhb_logs, only: [:show, :destroy] do
    resources :exhb_log_likes, only: [:create, :destroy]
    resources :exhb_log_comments, only: [:create, :destroy]
  end

  get 'exhb_logs/:id/exhb_log_comments' => 'exhb_logs#show'

  resources :arts, only: [:index, :show] do
    resources :art_logs, only: [:new, :create]
  end

  resources :art_logs, only: [:show, :destroy] do
    resources :art_log_likes, only: [:create, :destroy]
    resources :art_log_comments, only: [:create, :destroy]
  end

  get 'art_logs/:id/art_log_comments' => 'art_logs#show'

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }

  get 'articles/admin' => 'articles#admin_index'
  patch 'articles/:id/publish' => "articles#publish"
  put 'articles/:id/publish' => "articles#publish"
  patch 'articles/:id/unpublish' => "articles#unpublish"
  put 'articles/:id/unpublish' => "articles#unpublish"
  resources :articles

  get '/mypage' => 'users#mypage'
  get '/:username' => 'users#show'
  get '/:username/edit' => 'users#edit'
  patch '/:username' => 'users#update'
end

app/models/exhb_log.rb
class ExhbLog < ApplicationRecord
  belongs_to :user
  belongs_to :exhibition
  has_many :exhb_log_likes, dependent: :destroy
  has_many :exhb_log_comments, dependent: :destroy
  has_many :art_logs, dependent: :destroy
  accepts_nested_attributes_for :art_logs, allow_destroy: true

  validates :body, length: { maximum: 1000 }
end

app/controllers/exhb_logs_controller.rb
class ExhbLogsController < ApplicationController
  before_action :set_exhb_log, only: [:show, :edit, :update, :destroy]

  # GET /exhb_logs
  # GET /exhb_logs.json
  def index
    @exhb_logs = ExhbLog.all
  end

  # GET /exhb_logs/1
  # GET /exhb_logs/1.json
  def show
    @title = "アート・展覧会の感想を見るなら【doodo】"
    @exhb_log_comment = ExhbLogComment.new
    @exhb_log_comments = @exhb_log.exhb_log_comments
    @exhibition = @exhb_log.exhibition
    @museum = @exhibition.museum
  end

  # GET /exhb_logs/new
  def new
    @exhb_log = ExhbLog.new
  end

  # GET /exhb_logs/1/edit
  def edit
  end

  # POST /exhb_logs
  # POST /exhb_logs.json
  def create
    @exhb_log = ExhbLog.new(exhb_log_params)

    respond_to do |format|
      if @exhb_log.save
        format.html { redirect_to @exhb_log, notice: 'Exhb log was successfully created.' }
        format.json { render :show, status: :created, location: @exhb_log }
      else
        format.html { render :new }
        format.json { render json: @exhb_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exhb_logs/1
  # PATCH/PUT /exhb_logs/1.json
  def update
    respond_to do |format|
      if @exhb_log.update(exhb_log_params)
        format.html { redirect_to @exhb_log, notice: 'Exhb log was successfully updated.' }
        format.json { render :show, status: :ok, location: @exhb_log }
      else
        format.html { render :edit }
        format.json { render json: @exhb_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exhb_logs/1
  # DELETE /exhb_logs/1.json
  def destroy
    if user_signed_in?
      if @exhb_log.user.id == current_user.id || current_user.email == "admin@doodo.jp"
        @exhb_log.destroy
        Exhibition.update_star_by(@exhb_log)
        Art.update_stars_by(@exhb_log.art_logs)
      end
    end
    redirect_to session[:previous_url] || root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exhb_log
      unless @exhb_log = ExhbLog.find_by(id: params[:id])
        redirect_to search_path
      end
    end

    # Only allow a list of trusted parameters through.
    def exhb_log_params
      params.fetch(:exhb_log, {})
    end
end

app/helpers/exhb_logs_helper.rb
module ExhbLogsHelper
end

app/views/exhb_logs/_show.html.erb
<div class="row">
  <div class="col-3 col-4-xsmall">
    <h2>
        <span><i class="fas fa-star yellow"></i></span>
        <% if exhb_log.star.present? %>
          <span><%= exhb_log.star %></span>
        <% else %>
          <span>&nbsp;-&nbsp;</span>
        <% end %>
        <span class="denominator">/3</span>
      </h2>
  </div>

  <div class="col-9 col-8-xsmall">
    <%= link_to exhb_log_path(exhb_log) do %>
      <div id="exhb_log<%= exhb_log.id %>_body" class="dark mt5 mb10"><%= exhb_log.body %></div>
    <% end %>
    <div id="exhb_log<%= exhb_log.id %>_form" class="non-active mb5">
      <%= form_with(model: exhb_log, url: "/logs/#{exhb_log.id}", method: "PATCH") do |form| %>
        <%= form.text_area :body, value: exhb_log.body %>
        <div class="flex-container space-between">
          <div id="cancel_edit_exhb_log<%= exhb_log.id %>" class="button mt5">キャンセル</div>
          <%= form.submit "保存", id: "submit_exhb_log#{exhb_log.id}", class: "primary mt5" %>
        </div>
      <% end %>
    </div>
    <div class="mb10" style="font-size:0.8em;"><%= l exhb_log.created_at, format: :short_date %></div>

    <div class="row">
      <div class="col-7">
        <% if params[:controller] != "exhb_logs" %>
          <% if exhb_log.body.present? %>
            <a href="/exhb_logs/<%=exhb_log.id%>" class="button dark">コメントする</a>
          <% end %>
        <% end %>
      </div>
      <div class="col-5">
        <div id="exhb_log_like_<%= exhb_log.id %>">
          <%= render partial: "exhb_log_likes/button", locals: {exhb_log: exhb_log} %>
        </div>

        <div id="exhb_log_likes_count_<%= exhb_log.id %>">
          <%= render partial: "exhb_log_likes/count", locals: {exhb_log: exhb_log} %>
        </div>
      </div>
    </div>
  </div>

</div>


<script type="text/javascript" language="javascript">
    $('#cancel_edit_exhb_log<%= exhb_log.id %>').on('click', function () {
        $('#exhb_log<%= exhb_log.id %>_body').removeClass('non-active');
        $('#exhb_log<%= exhb_log.id %>_form').addClass('non-active')
    });

    $('#submit_exhb_log<%= exhb_log.id %>').on('click', function () {
        setTimeout(function () {
            location.reload();
        }, 500);
    });
</script>

app/views/exhb_logs/show.html.erb
<div class="row">
  <div class="col-6 col-12-xsmall">
    <div class="logs-container">
      <div class="mb10">
        <%= render partial: "users/show",
                   locals: {
                       item: @exhb_log,
                       item_name: "exhb_log",
                       destroy_url: "/exhb_logs/#{@exhb_log.id}"
                   } %>
        <%= render partial: "exhb_logs/show", locals: {exhb_log: @exhb_log} %>
      </div>

      <div class="row">
        <div class="off-1 col-10">
          <div class="mb10">
            <% @exhb_log_comments.each do |exhb_log_comment| %>
              <%= render partial: "users/show",
                         locals: {
                             item: exhb_log_comment,
                             item_name: "exhb_log_comment",
                             destroy_url: "/exhb_logs/#{@exhb_log.id}/exhb_log_comments/#{exhb_log_comment.id}"
                         } %>
              <div class="row mb10">
                <div class="off-3 col-9 off-2-xsmall col-10">
                  <%= exhb_log_comment.body %>
                </div>
              </div>
            <% end %>
          </div>

          <%= form_with(model: @exhb_log_comment, url: exhb_log_exhb_log_comments_path(@exhb_log)) do |form| %>
            <div class="mb10"><%= form.text_area :body, rows: 1, value: session[:exhb_log_comment_body], placeholder: "コメント..." %></div>
            <div class="align-right"><%= form.submit "送信", id: "submit_comment_button" %></div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="col-6 col-12-xsmall">
    <div class="log-exhibition-info-container">
      <header class="major align-center">
        <h3>
          <%= @exhibition.name %>
        </h3>
      </header>

      <%= link_to exhibition_path(@exhibition) do %>
        <div class="row">
          <% if @exhibition.image.present? %>
            <div class="off-3 col-6">
              <%= image_tag @exhibition.image, class: "image w100" %>
            </div>
          <% else %>
            <div class="off-3 col-6">
              <div class="adjust-box box-16x9">
                <div class="inner-box align-center">
                  <div class="icon fa-gem gray" style="font-size:4em;"></div>
                </div>
              </div>
              <div class="image"></div>
            </div>
          <% end %>
        </div>
      <% end %>

      <div class="align-center">
        <a href="/museums/<%= @museum.id %>" class="bb0"><%= @museum.name %></a>
      </div>

      <div class="align-center">
        <% if @exhibition.start_date.year == @exhibition.end_date.year %>
          <strong><%= l @exhibition.start_date, format: :long %></strong>
          <strong> 〜 </strong>
          <strong><%= l @exhibition.end_date, format: :short %></strong>
        <% else %>
          <strong><%= l @exhibition.start_date, format: :short %></strong>
          <strong> 〜 </strong>
          <strong><%= l @exhibition.end_date, format: :long %></strong>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript" language="javascript">
    $('#submit_comment_button').on('click', function () {
        setTimeout(function() {
            location.reload();
        }, 500);
    });
</script>