config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/trend' => 'pages#trend'
  get '/search' => 'pages#search'
  get '/post' => 'pages#post'

  resources :museums, only: [:index, :show]

  resources :logs, only: [:new, :create, :edit, :update]
  resources :art_logs, only: [:edit, :update]

  resources :exhibitions, only: [:index, :show] do
    resources :exhb_pins, only: [:create, :destroy]
  end

  resources :exhb_logs, only: [:show, :destroy] do
    resources :exhb_log_likes, only: [:create, :destroy]
    resources :exhb_log_comments, only: [:create, :destroy]
  end

  get 'exhb_logs/:id/exhb_log_comments' => 'exhb_logs#show'

  resources :arts, only: [:index, :show] do
    resources :art_logs, only: [:new, :create]
  end

  resources :art_logs, only: [:show, :destroy] do
    resources :art_log_likes, only: [:create, :destroy]
    resources :art_log_comments, only: [:create, :destroy]
  end

  get 'art_logs/:id/art_log_comments' => 'art_logs#show'

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }

  get 'articles/admin' => 'articles#admin_index'
  patch 'articles/:id/publish' => "articles#publish"
  put 'articles/:id/publish' => "articles#publish"
  patch 'articles/:id/unpublish' => "articles#unpublish"
  put 'articles/:id/unpublish' => "articles#unpublish"
  resources :articles

  get '/mypage' => 'users#mypage'
  get '/:username' => 'users#show'
  get '/:username/edit' => 'users#edit'
  patch '/:username' => 'users#update'
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update]
  before_action :set_exhibition, only: [:create]
  before_action :set_log, only: [:show, :edit, :update, :destroy]

  # GET /logs
  # GET /logs.json
  def index
    @logs = Log.all
  end

  # GET /logs/1
  # GET /logs/1.json
  def show
  end

  # GET /logs/new
  def new
    @title = "投稿ページ｜アート・展覧会の口コミなら【doodo】"
    @description = "アート・展覧会の口コミサイト「doodo」の投稿ページです。ログインすることで、アート・絵画・美術館・展覧会・美術展の口コミを投稿することができます。六本木、国立新美術館、上野、国立西洋美術館など、各地で開催されている展覧会の最新情報もご案内。"

    if params[:museum_area].present? || params[:museum_name].present?
      museums = Museum.where("address LIKE ?", "%#{params[:museum_area]}%").where("name LIKE ?", "%#{params[:museum_name]}%")
      @museums = museums.sort do |a,b|
        if !a.exhibitions.last.star.present?
          1
        elsif !b.exhibitions.last.star.present?
          -1
        else
          b <=> a
        end
      end
    else
      @museums = Museum.includes(:exhibitions).order("exhibitions.star DESC NULLS LAST")
    end
    @museums = @museums.select { |museum| museum.id != 1 }.first(24)

    if params[:any].present?
      @exhibitions = Exhibition.search_by_any(params).sort do |a,b|
        if !a.star.present?
          1
        elsif !b.star.present?
          -1
        else
          b <=> a
        end
      end
    elsif params[:exhb_area].present? || params[:exhb_name].present? || params[:exhb_date].present?
      @exhibitions = Exhibition.search_by(params).sort do |a,b|
        if !a.star.present?
          1
        elsif !b.star.present?
          -1
        else
          b <=> a
        end
      end
    else
      @exhibitions = Exhibition.order("star DESC NULLS LAST")
    end
    @exhibitions = @exhibitions.select { |exhb| exhb.id != 1 }.first(24)

    if params[:art_name].present? || params[:artist_name].present?
      arts = Art.search_by(params).first(24)
      @arts = arts.sort do |a,b|
        if !a.star.present?
          1
        elsif !b.star.present?
          -1
        else
          b <=> a
        end
      end
    else
      @arts = Art.order("star DESC NULLS LAST").first(24)
    end

  end

  # GET /logs/1/edit
  def edit
  end

  # POST /logs
  # POST /logs.json
  def create
    @exhb_log = ExhbLog.new(exhb_log_params)
    @exhb_log.user_id = current_user.id
    @exhb_log.exhibition_id = @exhibition.id

    @exhb_log.art_logs.each do |art_log|
      if (art_log.star == 0 || art_log.star.blank?) && (art_log.body.blank? && art_log.image.blank?)
        art_log.destroy
      else
        art_log.user_id = current_user.id
      end
    end

    if @exhb_log.save
      Exhibition.update_star_by(@exhb_log)
      Art.update_stars_by(@exhb_log.art_logs)
      redirect_to mypage_path
    else
      redirect_to new_exhibition_log_path
    end
  end

  # PATCH/PUT /logs/1
  # PATCH/PUT /logs/1.json
  def update
    if @log.user == current_user
      @log.update(body: exhb_log_params[:body])
    end
    redirect_to session[:previous_url] || root_path
  end

  # DELETE /logs/1
  # DELETE /logs/1.json
  def destroy
    @log.destroy
    respond_to do |format|
      format.html { redirect_to logs_url, notice: 'Log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_log
      @log = ExhbLog.find(params[:id])
    end

    def set_exhibition
      @exhibition = Exhibition.find(params[:exhibition_id])
    end

    # Only allow a list of trusted parameters through.
    def log_params
      params.fetch(:log, {})
    end

    def exhb_log_params
      params.fetch(:exhb_log, {}).permit(:star, :body, art_logs_attributes: [:art_id, :star, :body, :image])
    end
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/logs/_index.html.erb
<div class="row">
	<% exhb_logs.each do |exhb_log| %>
		<div class="col-6 col-12-xsmall mb20">
			<% if exhb_log.exhibition_id != 1 %>
				<header class="major align-center">
					<h3>
						<%= link_to exhb_log.exhibition.name, exhibition_path(exhb_log.exhibition) %>
					</h3>
				</header>

				<%= render partial: "users/show", locals: {user: exhb_log.user, body: exhb_log} %>
				<%= render partial: "exhb_logs/show", locals: {exhb_log: exhb_log} %>

				<div class="row">
					<% exhb_log.art_logs.each do |art_log| %>
						<div class="off-1 col-11">
							<%= render partial: "users/show", locals: {user: art_log.user, body: art_log} %>
							<%= render partial: "art_logs/show", locals: {art_log: art_log} %>
						</div>
					<% end %>
				</div>
			<% elsif (art_log = exhb_log.art_logs.first).present? %>
				<header class="major align-center">
					<h3>
						<%= link_to art_log.art.name, art_path(art_log.art) %>
					</h3>
				</header>

				<div class="row">
					<div class="col-12">
						<%= render partial: "users/show", locals: {user: art_log.user, body: art_log} %>
						<%= render partial: "art_logs/show", locals: {art_log: art_log} %>
					</div>
				</div>
			<% end %>

		</div>
	<% end %>
</div>

app/views/logs/_show.html.erb
<!--params: exhb_log-->
<% user = exhb_log.user %>
<% exhibition = exhb_log.exhibition %>
<% museum = exhibition.museum %>
<% art_logs = exhb_log.art_logs %>


<div class="log-container">
  <%= render partial: "users/show",
             locals: {
                 item: exhb_log,
                 item_name: "exhb_log",
                 destroy_url: "/exhb_logs/#{exhb_log.id}"
             } %>

  <div class="row mb5">
    <div class="col-8">
      <div class="log-body-container">
        <%= link_to exhb_log_path(exhb_log) do %>
          <h2 class="ml10 mb0">
            <% n = exhb_log.star.floor %>
            <% n.times do %>
              <span><i class="fas fa-star yellow"></i></span>
            <% end %>
            <% if n != exhb_log.star %>
              <% m = 3 - n - 1 %>
              <span><i class="fas fa-star-half yellow"></i></span>
            <% else %>
              <% m = 3 - n %>
            <% end %>
            <% m.times do %>
              <span><i class="fas fa-star light-gray"></i></span>
            <% end %>
            <span class="ml10"><%= exhb_log.star %></span>
            <span class="denominator">/3</span>
          </h2>
        <% end %>

        <%= link_to exhibition_path(exhibition) do %>
          <% if exhibition.name.length > 11 %>
            <div class="bold dark" style="font-size: 1.2em">展：<%= exhibition.name.first(10) %>...</div>
          <% else %>
            <div class="bold dark" style="font-size: 1.2em">展：<%= exhibition.name %></div>
          <% end %>
        <% end %>

        <%= link_to museum_path(museum) do %>
          <% if museum.name.length > 13 %>
            <div class="dark">館：<%= museum.name.first(12) %>...</div>
          <% else %>
            <div class="dark">館：<%= museum.name %></div>
          <% end %>
        <% end %>

        <%= link_to exhb_log_path(exhb_log) do %>
          <div id="exhb_log<%= exhb_log.id %>_body" class="dark mt5">
            <% if exhb_log.body.length > 199 %>
              <%= exhb_log.body.first(199) %>...
            <% else %>
              <%= exhb_log.body %>
            <% end %>
          </div>
        <% end %>
        <div id="exhb_log<%= exhb_log.id %>_form" class="non-active mb5">
          <%= form_with(model: exhb_log, url: "/logs/#{exhb_log.id}", method: "PATCH") do |form| %>
            <%= form.text_area :body, value: exhb_log.body %>
            <div class="flex-container space-between">
              <div id="cancel_edit_exhb_log<%= exhb_log.id %>" class="button mt5">キャンセル</div>
              <%= form.submit "保存", id: "submit_exhb_log#{exhb_log.id}", class: "primary mt5" %>
            </div>
          <% end %>
        </div>
        <%= link_to exhb_log_path(exhb_log) do %>
          <div class="gray" style="font-size:0.8em;"><%= l exhb_log.created_at, format: :short_date %></div>
        <% end %>

        <div class="reaction-buttons flex-container center">
          <div class="pl0">
            <div id="exhb_log_like_<%= exhb_log.id %>">
              <%= render partial: "exhb_log_likes/button", locals: {exhb_log: exhb_log} %>
            </div>
            <div id="exhb_log_likes_count_<%= exhb_log.id %>">
              <%= render partial: "exhb_log_likes/count", locals: {exhb_log: exhb_log} %>
            </div>
          </div>

          <div class="pl20">
            <% if exhb_log.body.present? %>
              <a href="/exhb_logs/<%= exhb_log.id %>" class="button gray">コメントする</a>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="col-4 pt5 pl0">
      <%= link_to exhibition_path(exhibition) do %>
        <% if exhibition.image.present? %>
          <div>
            <%= image_tag exhibition.image, class: "image w100" %>
          </div>
        <% else %>
          <div class="adjust-box box-1x1">
            <div class="inner-box align-center">
              <div class="flex-container vertical">
                <h3 class="gray mb0"><i class="fas fa-camera"></i></h3>
                <div class="gray">NO IMAGE</div>
              </div>
            </div>
          </div>
          <div class="image"></div>
        <% end %>
      <% end %>
    </div>
  </div>

  <% if art_logs.present? %>
    <div class="swiper-parent">
      <div class="swiper-container swiper<%= exhb_log.id %>">
        <div class="swiper-wrapper">
          <% art_logs.each do |art_log| %>
            <% art = art_log.art %>
            <div class="swiper-slide">
              <% if art_log.image.present? %>
                <%= link_to art_log_path(art_log) do %>
                  <div class="adjust-box box-1x1">
                    <div class="inner-box align-center">
                      <%= image_tag art_log.image.to_s, class: "w100 h100 image", style: "object-fit: cover;" %>

                      <div class="bg-art-stars"></div>
                      <% if art_log.body.present? %>
                        <div class="comment-icon">
                          <div class="flex-container space-evenly center w100 h100">
                            <i class="fas fa-comment-dots white"></i>
                          </div>
                        </div>
                      <% end %>
                      <div class="art-stars">
                        <% art_log.star.times do %>
                          <span class="star w20 pb5 mb0 yellow"><i class="fas fa-star"></i></span>
                        <% end %>
                      </div>
                      <div class="camera-icon">
                        <div class="flex-container space-evenly center w100 h100">
                          <i class="fas fa-camera white"></i>
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>
              <% else %>
                <%= link_to art_path(art) do %>
                  <div class="adjust-box box-1x1">
                    <div class="inner-box align-center">
                      <% if art.image.present? %>
                        <%= image_tag art.image, class: "w100 h100 image", style: "object-fit: cover;" %>
                      <% else %>
                        <i class="far fa-gem"></i>
                      <% end %>

                      <div class="bg-art-stars"></div>
                      <% if art_log.body.present? %>
                        <div class="comment-icon">
                          <div class="flex-container space-evenly center w100 h100">
                            <i class="fas fa-comment-dots white"></i>
                          </div>
                        </div>
                      <% end %>
                      <div class="art-stars">
                        <% art_log.star.times do %>
                          <span class="star w20 pb5 mb0 yellow"><i class="fas fa-star"></i></span>
                        <% end %>
                      </div>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
          <% end %>
        </div>
        <% if art_logs.count > 3 %>
          <div class="swiper-pagination page<%= exhb_log.id %> swiper-pagination-pink"></div>
        <% end %>
      </div>
      <% if art_logs.count > 3 %>
        <div class="swiper-button-prev prev<%= exhb_log.id %> swiper-button-dark"></div>
        <div class="swiper-button-next next<%= exhb_log.id %> swiper-button-dark"></div>
      <% end %>
    </div>
  <% end %>
</div>


<script type="text/javascript" language="javascript">
    $('#cancel_edit_exhb_log<%= exhb_log.id %>').on('click', function () {
        $('#exhb_log<%= exhb_log.id %>_body').removeClass('non-active');
        $('#exhb_log<%= exhb_log.id %>_form').addClass('non-active');
    });

    $('#submit_exhb_log<%= exhb_log.id %>').on('click', function () {
        setTimeout(function () {
            location.reload();
        }, 500);
    });
</script>

app/views/logs/_show_art_log.html.erb
<!--params: exhb_log-->
<% art_log = exhb_log.art_logs.first %>
<% user = art_log.user %>
<% art = art_log.art %>
<% artist = art.artist %>


<div class="log-container">
  <%= render partial: "users/show",
             locals: {
                 item: art_log,
                 item_name: "art_log",
                 destroy_url: "/art_logs/#{art_log.id}"
             } %>

  <div class="row mb5">
    <div class="col-8">
      <div class="log-body-container">
        <%= link_to art_log_path(art_log) do %>
          <h2 class="ml10 mb0">
            <% art_log.star.times do %>
              <span><i class="fas fa-star yellow"></i></span>
            <% end %>
            <% (3 - art_log.star).times do %>
              <span><i class="fas fa-star light-gray"></i></span>
            <% end %>
            <span class="ml10"><%= art_log.star.to_f %></span>
            <span class="denominator">/3</span>
          </h2>
        <% end %>

        <%= link_to art_path(art) do %>
          <% if art.name.length > 11 %>
            <div class="bold dark" style="font-size: 1.2em">題：<%= art.name.first(10) %>...</div>
          <% else %>
            <div class="bold dark" style="font-size: 1.2em">題：<%= art.name %></div>
          <% end %>
        <% end %>

        <% if artist.name.length > 13 %>
          <div class="dark">作：<%= artist.name.first(12) %>...</div>
        <% else %>
          <div class="dark">作：<%= artist.name %></div>
        <% end %>

        <%= link_to art_log_path(art_log) do %>
          <div id="art_log<%= art_log.id %>_body" class="dark mt5">
            <% if art_log.body.length > 199 %>
              <%= art_log.body.first(199) %>...
            <% else %>
              <%= art_log.body %>
            <% end %>
          </div>
        <% end %>
        <div id="art_log<%= art_log.id %>_form" class="non-active mb5">
          <%= form_with(model: art_log, url: "/art_logs/#{art_log.id}", method: "PATCH") do |form| %>
            <%= form.text_area :body, value: art_log.body %>
            <div class="flex-container space-between">
              <div id="cancel_edit_art_log<%= art_log.id %>" class="button mt5">キャンセル</div>
              <%= form.submit "保存", id: "submit_art_log#{art_log.id}", class: "primary mt5" %>
            </div>
          <% end %>
        </div>
        <%= link_to art_log_path(art_log) do %>
          <div class="gray" style="font-size:0.8em;"><%= l art_log.created_at, format: :short_date %></div>
        <% end %>

        <div class="reaction-buttons flex-container center">
          <div class="pl0">
            <div id="art_log_like_<%= art_log.id %>">
              <%= render partial: "art_log_likes/button", locals: {art_log: art_log} %>
            </div>
            <div id="art_log_likes_count_<%= art_log.id %>">
              <%= render partial: "art_log_likes/count", locals: {art_log: art_log} %>
            </div>
          </div>

          <div class="pl20">
            <% if art_log.body.present? %>
              <a href="/art_logs/<%=art_log.id%>" class="button gray">コメントする</a>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <div class="col-4 pt5 pl0">
      <% if art_log.image.present? %>
        <%= link_to art_log_path(art_log) do %>
          <div style="position:relative;">
            <%= image_tag art_log.image.to_s, class: "image w100" %>
            <div class="bg-art-log">
              <div class="flex-container space-evenly center w100 h100">
                <i class="fas fa-camera white"></i>
              </div>
            </div>
          </div>
        <% end %>
      <% elsif art.image.present? %>
        <%= link_to art_path(art) do %>
          <div>
            <%= image_tag art.image, class: "image w100" %>
          </div>
        <% end %>
      <% else %>
        <%= link_to art_path(art) do %>
          <div class="adjust-box box-1x1">
            <div class="inner-box align-center">
              <span class="icon fa-gem gray" style="font-size:4em;"></span>
            </div>
          </div>
          <div class="image"></div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>


<script type="text/javascript" language="javascript">
    $('#cancel_edit_art_log<%= art_log.id %>').on('click', function () {
        $('#art_log<%= art_log.id %>_body').removeClass('non-active');
        $('#art_log<%= art_log.id %>_form').addClass('non-active');
    });

    $('#submit_art_log<%= art_log.id %>').on('click', function () {
        setTimeout(function () {
            location.reload();
        }, 500);
    });
</script>

app/views/logs/new_old.html.erb
<section>
  <div class="row mb10">
		<div class="off-3 col-2 off-1-xsmall col-4-xsmall">
			<div class="align-center disabled w100">
				<i class="fas fa-search light-gray"></i>
				<div class="light-gray">展覧会を探す</div>
			</div>
		</div>
		<div class="col-2 col-1-xsmall">
			<h2 class="align-center w100 mt5">
				<i class="fas fa-arrow-right"></i>
			</h2>
		</div>
		<div class="col-2 off-0-xsmall col-5-xsmall">
			<h3 class="align-center w100">
				<i class="fas fa-edit dark"></i>
				<div class="dark">感想を残す</div>
			</h3>
		</div>
	</div>

  <header class="major align-center">
    <h2><%= @exhibition.name %></h2>
  </header>

  <%= form_for(@exhb_log, url: exhibition_logs_path) do |exhb_log_form| %>
    <div class="row gtr-uniform">
      <h1 class="col-12 row">
        <div class="col-5 col-8-xsmall">
          <input type="range" class="input-range" min="0.0" max="3.0" step="0.5" value="0.0" name="exhb_log[star]" id="exhb_log_star">
        </div>
        <div class="col-1">
          <i class="fas fa-star yellow"></i>
        </div>
        <div class="col-2">
          <span id="exhb_star">0.0</span>
        </div>
      </h1>

      <div class="col-8 col-12-xsmall">
        <%= exhb_log_form.text_area :body, size: "30x1", placeholder: "感想..." %>
      </div>

      <div class="col-4 col-12-xsmall">
        <div class="w100 align-right">
          <input type="submit" name="commit" value="保存" data-disable-with="保存中" class="w30 primary"/>
        </div>
      </div>
    </div>

    <div class="mt20">
      <% if @arts.present? %>
        <header class="major align-center">
          <h2>作品のログも残す</h2>
        </header>

        <div class="row">
          <% @arts.each.with_index do |art, i| %>
            <div class="col-6 col-12-xsmall">
              <%= exhb_log_form.fields_for :art_logs do |art_log_fields| %>
                <%= art_log_fields.hidden_field :art_id, value: art.id %>
                <div class="row mb20">
                  <div class="col-5">
                    <div id="art<%=i%>_img_field" onclick="$('#exhb_log_art_logs_attributes_<%= i %>_image').click()">
                      <% if art.image.present? %>
                        <%= image_tag art.image, class: "image w100" %>
                      <% else %>
                        <div class="adjust-box box-16x9">
                          <div class="inner-box align-center">
                            <div class="icon fa-gem gray" style="font-size:3em;"></div>
                          </div>
                        </div>
                        <div class="image"></div>
                      <% end %>
                    </div>

                    <%= art_log_fields.file_field :image, style: "display:none;" %>
                    <label for="exhb_log_art_logs_attributes_<%= i %>_image" class="mb0">
                      <div class="button small w100" id="art<%= i %>_img_upload_button">画像をアップロード</div>
                    </label>
                  </div>

                  <div class="col-7 b0">
                    <strong><%= art.name %></strong>
                    <div><%= art.artist.name %>作</div>
                    <% if art.year.present? %>
                      <div>（<%= art.year %>年）</div>
                    <% end %>

                    <%= art_log_fields.hidden_field :star, value: 0 %>
                    <div class="col-4 col-5-xsmall">
                      <h2 class="mobile-fs2em mt10 mb10">
                        <span id="art<%= i %>_star1" class="star mb0 light-gray"><i class="fas fa-star"></i></span>
                        <span id="art<%= i %>_star2" class="star mb0 light-gray"><i class="fas fa-star"></i></span>
                        <span id="art<%= i %>_star3" class="star mb0 light-gray"><i class="fas fa-star"></i></span>
                      </h2>
                    </div>

                    <%= art_log_fields.text_area :body, rows: 1, placeholder: "感想..." %>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>

      <div class="w100 align-right">
        <input type="submit" name="commit" value="すべて保存" data-disable-with="保存中" class="w30 primary"/>
      </div>
    </div>
  <% end %>
</section>


<script type="text/javascript" language="javascript">
  var exhb_slider = $('#exhb_log_star')[0];
  var exhb_star_count = $('#exhb_star')[0];
  exhb_slider.oninput = function () {
      exhb_star_count.textContent = Number(exhb_slider.value).toFixed(1);
  };

  <% @arts.each.with_index do |art, i| %>
    $(function(){
      $art<%= i %>_fileField = $('#exhb_log_art_logs_attributes_<%= i %>_image')
      $art<%= i %>_preview = $("#art<%= i %>_img_field");
      $art<%= i %>_img_upload_button = $("#art<%= i %>_img_upload_button");

      // 選択された画像を取得し表示
      $($art<%= i %>_fileField).on('change', $art<%= i %>_fileField, function(e) {
        file = e.target.files[0];
        reader = new FileReader();

        if(file.type.indexOf('image') < 0){
          return false;
        };

        reader.onload = (function(file) {
          return function(e) {
            $art<%= i %>_preview.empty();
            $art<%= i %>_preview.append($('<img>').attr({
              src: e.target.result,
              width: "100%",
              title: file.name
            }));
            $art<%= i %>_img_upload_button.text("画像を変更");
            $art<%= i %>_img_upload_button.addClass("primary");
          };
        })(file);
        reader.readAsDataURL(file);
      });
    });

    var art<%= i %>_star1 = $('#art<%= i %>_star1')[0];
    var art<%= i %>_star2 = $('#art<%= i %>_star2')[0];
    var art<%= i %>_star3 = $('#art<%= i %>_star3')[0];

    function art<%= i %>_star0_func() {
        $('#art<%= i %>_star1').removeClass('yellow');
        $('#art<%= i %>_star1').addClass('light-gray');
        $('#art<%= i %>_star2').removeClass('yellow');
        $('#art<%= i %>_star2').addClass('light-gray');
        $('#art<%= i %>_star3').removeClass('yellow');
        $('#art<%= i %>_star3').addClass('light-gray');
        $('#exhb_log_art_logs_attributes_<%= i %>_star').val(0);
    }

    function art<%= i %>_star1_func() {
        $('#art<%= i %>_star1').removeClass('light-gray');
        $('#art<%= i %>_star1').addClass('yellow');
        $('#art<%= i %>_star2').removeClass('yellow');
        $('#art<%= i %>_star2').addClass('light-gray');
        $('#art<%= i %>_star3').removeClass('yellow');
        $('#art<%= i %>_star3').addClass('light-gray');
        $('#exhb_log_art_logs_attributes_<%= i %>_star').val(1);
    }

    function art<%= i %>_star2_func() {
        $('#art<%= i %>_star1').removeClass('light-gray');
        $('#art<%= i %>_star1').addClass('yellow');
        $('#art<%= i %>_star2').removeClass('light-gray');
        $('#art<%= i %>_star2').addClass('yellow');
        $('#art<%= i %>_star3').removeClass('yellow');
        $('#art<%= i %>_star3').addClass('light-gray');
        $('#exhb_log_art_logs_attributes_<%= i %>_star').val(2);
    }

    function art<%= i %>_star3_func() {
        $('#art<%= i %>_star1').removeClass('light-gray');
        $('#art<%= i %>_star1').addClass('yellow');
        $('#art<%= i %>_star2').removeClass('light-gray');
        $('#art<%= i %>_star2').addClass('yellow');
        $('#art<%= i %>_star3').removeClass('light-gray');
        $('#art<%= i %>_star3').addClass('yellow');
        $('#exhb_log_art_logs_attributes_<%= i %>_star').val(3);
    }

    art<%= i %>_star1.onclick = function () {
        if (!($('#art<%= i %>_star1').hasClass('yellow'))) {
            art<%= i %>_star1_func();
        } else if (!($('#art<%= i %>_star2').hasClass('yellow'))) {
            art<%= i %>_star0_func();
        } else if (!($('#art<%= i %>_star3').hasClass('yellow'))) {
            art<%= i %>_star1_func();
        } else {
            art<%= i %>_star1_func();
        }
    };
    art<%= i %>_star2.onclick = function () {
        if (!($('#art<%= i %>_star1').hasClass('yellow'))) {
            art<%= i %>_star2_func();
        } else if (!($('#art<%= i %>_star2').hasClass('yellow'))) {
            art<%= i %>_star2_func();
        } else if (!($('#art<%= i %>_star3').hasClass('yellow'))) {
            art<%= i %>_star1_func();
        } else {
            art<%= i %>_star2_func();
        }
    };
    art<%= i %>_star3.onclick = function () {
        if (!($('#art<%= i %>_star1').hasClass('yellow'))) {
            art<%= i %>_star3_func();
        } else if (!($('#art<%= i %>_star2').hasClass('yellow'))) {
            art<%= i %>_star3_func();
        } else if (!($('#art<%= i %>_star3').hasClass('yellow'))) {
            art<%= i %>_star3_func();
        } else {
            art<%= i %>_star2_func();
        }
    };
  <% end %>
</script>