config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/trend' => 'pages#trend'
  get '/search' => 'pages#search'
  get '/post' => 'pages#post'

  resources :museums, only: [:index, :show]

  resources :logs, only: [:new, :create, :edit, :update]
  resources :art_logs, only: [:edit, :update]

  resources :exhibitions, only: [:index, :show] do
    resources :exhb_pins, only: [:create, :destroy]
  end

  resources :exhb_logs, only: [:show, :destroy] do
    resources :exhb_log_likes, only: [:create, :destroy]
    resources :exhb_log_comments, only: [:create, :destroy]
  end

  get 'exhb_logs/:id/exhb_log_comments' => 'exhb_logs#show'

  resources :arts, only: [:index, :show] do
    resources :art_logs, only: [:new, :create]
  end

  resources :art_logs, only: [:show, :destroy] do
    resources :art_log_likes, only: [:create, :destroy]
    resources :art_log_comments, only: [:create, :destroy]
  end

  get 'art_logs/:id/art_log_comments' => 'art_logs#show'

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }

  get 'articles/admin' => 'articles#admin_index'
  patch 'articles/:id/publish' => "articles#publish"
  put 'articles/:id/publish' => "articles#publish"
  patch 'articles/:id/unpublish' => "articles#unpublish"
  put 'articles/:id/unpublish' => "articles#unpublish"
  resources :articles

  get '/mypage' => 'users#mypage'
  get '/:username' => 'users#show'
  get '/:username/edit' => 'users#edit'
  patch '/:username' => 'users#update'
end

app/models/art_log.rb
class ArtLog < ApplicationRecord
  belongs_to :user
  belongs_to :exhb_log
  belongs_to :art
  has_many :art_log_likes, dependent: :destroy
  has_many :art_log_comments, dependent: :destroy

  mount_uploader :image, ImageUploader

  validates :body, length: { maximum: 1000 }
end

app/controllers/art_logs_controller.rb
class ArtLogsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update]
  before_action :set_art_log, only: [:show, :edit, :update, :destroy]
  before_action :set_art, only: [:new, :create]

  # GET /art_logs
  # GET /art_logs.json
  def index
    @art_logs = ArtLog.all
  end

  # GET /art_logs/1
  # GET /art_logs/1.json
  def show
    @title = "アート・展覧会の感想を見るなら【doodo】"
    @art_log_comment = ArtLogComment.new
    @art_log_comments = @art_log.art_log_comments
    @art = @art_log.art
    @exhibition = @art.exhibition
    @museum = @exhibition.museum
  end

  # GET /art_logs/new
  def new
    @title = "投稿ページ｜アート・展覧会の感想を見るなら【doodo】"
    @description = "アート・展覧会の感想まとめサイト「doodo」の投稿ページです。ログインすることで、アート・絵画・美術館・展覧会・美術展の感想を投稿することができます。六本木、国立新美術館、上野、国立西洋美術館など、各地で開催されている展覧会の最新情報もご案内。"
    @exhb_log = ExhbLog.new
    @exhb_log.art_logs.build
  end

  # GET /art_logs/1/edit
  def edit
  end

  # POST /art_logs
  # POST /art_logs.json
  def create
    @exhb_log = ExhbLog.new(exhb_log_params)
    @exhb_log.user_id = current_user.id
    @exhb_log.exhibition_id = 1

    @art_log = @exhb_log.art_logs.first
    @art_log.user_id = current_user.id

    if @exhb_log.save
      @art_log.art.update_star
      redirect_to mypage_path
    else
      redirect_to new_art_art_log_path
    end
  end

  # PATCH/PUT /art_logs/1
  # PATCH/PUT /art_logs/1.json
  def update
    if @art_log.user == current_user
      @art_log.update(body: art_log_params[:body])
    end
    redirect_to session[:previous_url] || root_path
  end

  # DELETE /art_logs/1
  # DELETE /art_logs/1.json
  def destroy
    if user_signed_in?
      if @art_log.user.id == current_user.id || current_user.email == "admin@doodo.jp"
        if @art_log.exhb_log.exhibition.id == 1
          @art_log.exhb_log.destroy
          @art_log.art.update_star
        else
          @art_log.destroy
          @art_log.art.update_star
        end
      end
    end
    redirect_to session[:previous_url] || root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_art_log
      unless @art_log = ArtLog.find_by(id: params[:id])
        redirect_to "#{search_path}?t=art"
      end
    end

    def set_art
      @art = Art.find(params[:art_id])
    end

    # Only allow a list of trusted parameters through.
    def art_log_params
      params.fetch(:art_log, {})
    end

    def exhb_log_params
      params.fetch(:exhb_log, {}).permit(art_logs_attributes: [:art_id, :star, :body, :image])
    end
end

app/helpers/art_logs_helper.rb
module ArtLogsHelper
end

app/views/art_logs/_new.html.erb
<div class="adjust-box box-1x1">
  <div class="inner-box align-center">
    <% if art.image.present? %>
      <%= image_tag art.image, id: "art_log_#{i}", class: "w100 h100 image", style: "object-fit: cover;" %>
    <% else %>
      <i class="far fa-gem" id="art_log_<%= i %>"></i>
    <% end %>


    <div class="bg-art-stars"></div>
    <div class="flex-container center art-stars">
      <h3 class="mb0">
        <span class="art<%= i %>_star1 star mb0 light-gray"><i class="fas fa-star"></i></span>
        <span class="art<%= i %>_star2 star mb0 light-gray"><i class="fas fa-star"></i></span>
        <span class="art<%= i %>_star3 star mb0 light-gray"><i class="fas fa-star"></i></span>
      </h3>
    </div>
  </div>
</div>

<div class="align-center dark"><%= art.name.first(6) %><% if art.name.length > 6 %>...<% end %></div>

app/views/art_logs/_show.html.erb
<div class="row mb10">
  <% if art_log.image.present? %>
    <a href="/art_logs/<%=art_log.id%>" class="image off-3 col-6 off-0-xsmall col-12-xsmall">
      <%= image_tag art_log.image_url(:thumb), class: "w100" %>
    </a>
  <% elsif params[:controller] != "arts" && art_log.art.image.present? %>
    <div class="image off-3 col-6 off-2-xsmall col-8-xsmall">
      <%= link_to art_path(art_log.art) do %>
        <%= image_tag art_log.art.image, class: "image w100" %>
      <% end %>
    </div>
  <% end %>
</div>


<div class="row">
  <div class="col-4 col-4-xsmall">
    <% art_log.star.present? ? count = art_log.star : count = 0 %>
    <h2 class="align-center">
      <% count.times do %>
        <span><i class="fas fa-star yellow"></i></span>
      <% end %>
      <% (3 - count).times do %>
        <span><i class="fas fa-star light-gray"></i></span>
      <% end %>
    </h2>
  </div>

  <div class="col-8 col-8-xsmall">
    <% if params[:controller] != "arts" %>
      <%= link_to art_path(art_log.art) do %>
        <div class="bold dark bb0"><%= art_log.art.name %></div>
        <div class="gray"><%= art_log.art.artist.name %>作</div>
        <% if art_log.art.year.present? %>
          <div class="gray">（<%= art_log.art.year %>年）</div>
        <% end %>
      <% end %>
    <% end %>
    <%= link_to art_log_path(art_log) do %>
      <div id="art_log<%= art_log.id %>_body" class="dark mt5 mb10"><%= art_log.body %></div>
    <% end %>
    <div id="art_log<%= art_log.id %>_form" class="non-active mb5">
      <%= form_with(model: art_log, url: "/art_logs/#{art_log.id}", method: "PATCH") do |form| %>
        <%= form.text_area :body, value: art_log.body %>
        <div class="flex-container space-between">
          <div id="cancel_edit_art_log<%= art_log.id %>" class="button mt5">キャンセル</div>
          <%= form.submit "保存", id: "submit_art_log#{art_log.id}", class: "primary mt5" %>
        </div>
      <% end %>
    </div>
    <div class="mb10" style="font-size:0.8em;"><%= l art_log.created_at, format: :short_date %></div>

    <div class="row">
      <div class="col-7">
        <% if params[:controller] != "art_logs" %>
          <% if art_log.body.present? %>
            <a href="/art_logs/<%=art_log.id%>" class="button dark">コメントする</a>
          <% end %>
        <% end %>
      </div>

      <div class="col-5">
        <span id="art_log_like_<%= art_log.id %>">
          <%= render partial: "art_log_likes/button", locals: {art_log: art_log} %>
        </span>
        <span id="art_log_likes_count_<%= art_log.id %>">
          <%= render partial: "art_log_likes/count", locals: {art_log: art_log} %>
        </span>
      </div>
    </div>
  </div>
</div>


<script type="text/javascript" language="javascript">
    $('#cancel_edit_art_log<%= art_log.id %>').on('click', function () {
        $('#art_log<%= art_log.id %>_body').removeClass('non-active');
        $('#art_log<%= art_log.id %>_form').addClass('non-active')
    });

    $('#submit_art_log<%= art_log.id %>').on('click', function () {
        setTimeout(function () {
            location.reload();
        }, 500);
    });
</script>

app/views/art_logs/new.html.erb
<section>
  <div class="row mb10">
		<div class="off-3 col-2 off-1-xsmall col-4-xsmall">
			<div class="align-center disabled w100">
				<i class="fas fa-search light-gray"></i>
				<div class="light-gray">作品を探す</div>
			</div>
		</div>
		<div class="col-2 col-1-xsmall">
			<h2 class="align-center w100 mt5">
				<i class="fas fa-arrow-right"></i>
			</h2>
		</div>
		<div class="col-2 off-0-xsmall col-5-xsmall">
			<h3 class="align-center w100">
				<i class="fas fa-edit dark"></i>
				<div class="dark">感想を残す</div>
			</h3>
		</div>
	</div>

  <header class="major align-center">
    <h2><%= @art.name %></h2>
  </header>


  <div class="row">
    <div class="off-3 col-6 off-0-xsmall col-12-xsmall">
      <% if @art.image.present? %>
        <%= image_tag @art.image, class: "image w100" %>
      <% else %>
        <div class="adjust-box box-16x9">
          <div class="inner-box align-center">
            <div class="icon fa-gem gray" style="font-size:3em;"></div>
          </div>
        </div>
        <div class="image"></div>
      <% end %>

      <div class="align-center">
        <strong><%= @art.name %></strong>
        <div><%= @art.artist.name %>作</div>
        <% if @art.year.present? %>
          <div>（<%= @art.year %>年）</div>
        <% end %>
      </div>

      <%= form_for(@exhb_log, url: art_art_logs_path) do |exhb_log_form| %>
        <%= exhb_log_form.fields_for :art_logs do |art_log_fields| %>
          <%= art_log_fields.hidden_field :art_id, value: @art.id %>
          <%= art_log_fields.hidden_field :star, value: 0 %>
          <h1 class="align-center mb10">
            <span id="star1" class="star mb0 light-gray"><i class="fas fa-star"></i></span>
            <span id="star2" class="star mb0 light-gray"><i class="fas fa-star"></i></span>
            <span id="star3" class="star mb0 light-gray"><i class="fas fa-star"></i></span>
          </h1>
          <div class="mb10">
            <%= art_log_fields.text_area :body, rows: 1, placeholder: "感想..." %>
          </div>
        <% end %>
        <div class="align-right">
          <input type="submit" name="commit" value="保存" data-disable-with="保存中" class="w30 primary"/>
        </div>
      <% end %>
    </div>
  </div>
</section>

<script type="text/javascript" language="javascript">
    var star1 = $('#star1')[0];
    var star2 = $('#star2')[0];
    var star3 = $('#star3')[0];

    function star0_func() {
        $('#star1').removeClass('yellow');
        $('#star1').addClass('light-gray');
        $('#star2').removeClass('yellow');
        $('#star2').addClass('light-gray');
        $('#star3').removeClass('yellow');
        $('#star3').addClass('light-gray');
        $('#exhb_log_art_logs_attributes_0_star').val(0);
    }

    function star1_func() {
        $('#star1').removeClass('light-gray');
        $('#star1').addClass('yellow');
        $('#star2').removeClass('yellow');
        $('#star2').addClass('light-gray');
        $('#star3').removeClass('yellow');
        $('#star3').addClass('light-gray');
        $('#exhb_log_art_logs_attributes_0_star').val(1);
    }

    function star2_func() {
        $('#star1').removeClass('light-gray');
        $('#star1').addClass('yellow');
        $('#star2').removeClass('light-gray');
        $('#star2').addClass('yellow');
        $('#star3').removeClass('yellow');
        $('#star3').addClass('light-gray');
        $('#exhb_log_art_logs_attributes_0_star').val(2);
    }

    function star3_func() {
        $('#star1').removeClass('light-gray');
        $('#star1').addClass('yellow');
        $('#star2').removeClass('light-gray');
        $('#star2').addClass('yellow');
        $('#star3').removeClass('light-gray');
        $('#star3').addClass('yellow');
        $('#exhb_log_art_logs_attributes_0_star').val(3);
    }

    star1.onclick = function () {
        if (!($('#star1').hasClass('yellow'))) {
            star1_func();
        } else if (!($('#star2').hasClass('yellow'))) {
            star0_func();
        } else if (!($('#star3').hasClass('yellow'))) {
            star1_func();
        } else {
            star1_func();
        }
    };
    star2.onclick = function () {
        if (!($('#star1').hasClass('yellow'))) {
            star2_func();
        } else if (!($('#star2').hasClass('yellow'))) {
            star2_func();
        } else if (!($('#star3').hasClass('yellow'))) {
            star1_func();
        } else {
            star2_func();
        }
    };
    star3.onclick = function () {
        if (!($('#star1').hasClass('yellow'))) {
            star3_func();
        } else if (!($('#star2').hasClass('yellow'))) {
            star3_func();
        } else if (!($('#star3').hasClass('yellow'))) {
            star3_func();
        } else {
            star2_func();
        }
    };
</script>

app/views/art_logs/show.html.erb
<div class="row">
  <div class="col-6 col-12-xsmall">
    <div class="logs-container">
      <div class="mb10">
        <%= render partial: "users/show",
                   locals: {
                       item: @art_log,
                       item_name: "art_log",
                       destroy_url: "/art_logs/#{@art_log.id}"
                   } %>
        <%= render partial: "art_logs/show", locals: {art_log: @art_log} %>
      </div>

      <div class="row">
        <div class="off-1 col-10">
          <div class="mb10">
            <% @art_log_comments.each do |art_log_comment| %>
              <%= render partial: "users/show",
                         locals: {
                             item: art_log_comment,
                             item_name: "art_log_comment",
                             destroy_url: "/art_logs/#{@art_log.id}/art_log_comments/#{art_log_comment.id}"
                         } %>
              <div class="row mb10">
                <div class="off-3 col-9 off-2-xsmall col-10">
                  <%= art_log_comment.body %>
                </div>
              </div>
            <% end %>
          </div>

          <%= form_with(model: @art_log_comment, url: art_log_art_log_comments_path(@art_log)) do |form| %>
            <div class="mb10"><%= form.text_area :body, rows: 1, value: session[:art_log_comment_body], placeholder: "コメント..." %></div>
            <div class="align-right"><%= form.submit "送信", id: "submit_comment_button" %></div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="col-6 col-12-xsmall">
    <% if @exhibition.id != 1%>
      <div class="log-exhibition-info-container">
        <header class="major align-center">
          <h2>この作品が展示された展覧会</h2>
        </header>

        <%= link_to exhibition_path(@exhibition) do %>
          <div class="row">
            <% if @exhibition.image.present? %>
              <div class="off-3 col-6">
                <%= image_tag @exhibition.image, class: "image w100" %>
              </div>
            <% else %>
              <div class="off-3 col-6">
                <div class="adjust-box box-16x9">
                  <div class="inner-box align-center">
                    <div class="icon fa-gem gray" style="font-size:4em;"></div>
                  </div>
                </div>
                <div class="image"></div>
              </div>
            <% end %>
          </div>
        <% end %>

        <div class="align-center">
          <%= link_to @exhibition.name, exhibition_path(@exhibition), class: "bb0" %>
        </div>

        <div class="align-center">
          <a href="/museums/<%=@museum.id%>" class="bb0 dark"><%= @museum.name %></a>
        </div>

        <div class="align-center">
          <% if @exhibition.start_date.year == @exhibition.end_date.year %>
            <strong><%= l @exhibition.start_date, format: :long %></strong>
            <strong> 〜 </strong>
            <strong><%= l @exhibition.end_date, format: :short %></strong>
          <% else %>
            <strong><%= l @exhibition.start_date, format: :short %></strong>
            <strong> 〜 </strong>
            <strong><%= l @exhibition.end_date, format: :long %></strong>
          <% end %>
        </div>
      </div>
    <% else %>
      <div class="log-exhibition-info-container">
        <%= link_to art_path(@art) do %>
          <div class="row">
            <% if @art.image.present? %>
              <div class="off-3 col-6">
                <%= image_tag @art.image, class: "image w100" %>
              </div>
            <% else %>
              <div class="off-3 col-6">
                <div class="adjust-box box-16x9">
                  <div class="inner-box align-center">
                    <div class="icon fa-gem gray" style="font-size:4em;"></div>
                  </div>
                </div>
                <div class="image"></div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>


<script type="text/javascript" language="javascript">
    $('#submit_comment_button').on('click', function () {
        setTimeout(function() {
            location.reload();
        }, 500);
    });
</script>